name: Deploy to schwungus.software

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: website
      - name: Copy the files
        uses: appleboy/scp-action@v0.1.4
        with:
          source: website
          target: ${{ secrets.WEBSITE_PATH }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          rm: true
