name: Deploy to schwungus.software

on:
  push:
    branches: ["deploy"]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to schwungus.software
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3 python3-venv python3-pip
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: deploy
      - name: Build
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          ./build.py
      - name: Copy the files
        uses: appleboy/scp-action@v0.1.4
        with:
          source: ${{ github.workspace }}/out
          rm: true
          strip_components: 1
          target: ${{ secrets.WEBSITE_PATH }}/website
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
