name: Deploy to schwungus.software

on:
  push:
    branches: ["deploy"]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to schwungus.software
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: deploy
      - name: Produce output files
        run: |
          rm -rf out
          mkdir -p out
          cp -r index.html wavy.js index.css wavy.css sitemap.xml robots.txt assets/ out
      - name: Copy the output files onto the server
        uses: appleboy/scp-action@v0.1.4
        with:
          source: ${{ github.workspace }}/out
          rm: true
          strip_components: 1
          target: ${{ secrets.WEBSITE_PATH }}/website
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
