name: Deploy to schwungus.software

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    name: Deploy to schwungus.software
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install bash nodejs npm j2cli
          sudo npm -g install sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: deploy
      - name: Build
        run: |
          ./build.sh
      - name: Copy the files
        uses: appleboy/scp-action@v0.1.4
        with:
          source: ${{ github.workspace }}/out
          rm: true
          strip_components: 1
          target: ${{ secrets.WEBSITE_PATH }}/website
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
